photos/gallery/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import ArchiveView, PhotoDetailView

urlpatterns = [
    url(r'^$', ArchiveView.as_view(), name='archive'),
    url(r'^last/$', PhotoDetailView.as_view(), name='photo_detail'),
    url(r'^(?P<slug>[^/]+)$', PhotoDetailView.as_view(), name='photo_detail'),

]

photos/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views
from .gallery.views import ArchiveView, PhotoDetailView, ArchiveApiView

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^archive/', include('photos.gallery.urls', namespace='gallery')),
    url(r'^api/archive/', ArchiveApiView.as_view()),

    url(r'^u/(?P<username>[a-z0-9]+)/archive/$', ArchiveView.as_view(), name='user_archive'),
    url(r'^api/u/(?P<username>[a-z0-9]+)/archive/$', ArchiveApiView.as_view(),
        name='user_api_archive'),
    url(r'^u/(?P<username>[a-z0-9]+)/$', PhotoDetailView.as_view(), name='user_home'),

    url(r'^admin/', admin.site.urls),
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photos/gallery/models.py
# -*- coding: utf-8 -*-
from django.core.cache import cache
from django.db import models
from django.utils.functional import cached_property
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from PIL import Image
from PIL.ExifTags import TAGS
from thumbnails import get_thumbnail


def photo_upload_to(instance, filename):
    return 'photos/user_{0}/{1}'.format(instance.user.id, filename)


class Photo(models.Model):
    user = models.ForeignKey('users.User', related_name='photos')
    file = models.ImageField(upload_to=photo_upload_to)
    title = models.CharField(max_length=150)
    slug = models.CharField(max_length=160, db_index=True, blank=True)
    taken_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ['user', 'slug']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return "{0}/archive/{1}".format(self.user.get_absolute_url(), self.slug)

    @property
    def large_thumbnail(self):
        return get_thumbnail(self.file.path, '3000')

    @property
    def medium_thumbnail(self):
        return get_thumbnail(self.file.path, '1000')

    @property
    def archive_thumbnail(self):
        return self.square_thumbnail('500x500')

    def square_thumbnail(self, size='1000x1000'):
        return get_thumbnail(self.file.path, size, crop='center')

    @property
    def admin_thumbnail(self):
        return mark_safe('<img src="{}" alt="{}" />'.format(
            get_thumbnail(self.file.path, '150').url,
            self.title
        ))

    @property
    def camera(self):
        return self.exif.get('Model')

    @property
    def lens(self):
        return self.exif.get('LensModel')

    @property
    def exposure_time(self):
        return '{}/{}'.format(self.exif.get('ExposureTime')[0], self.exif.get('ExposureTime')[1])

    @property
    def aperture(self):
        return self.exif.get('FNumber')[0] / self.exif.get('FNumber')[1]

    @property
    def focal_length(self):
        return int(self.exif.get('FocalLength')[0] / self.exif.get('FocalLength')[1])

    @property
    def iso(self):
        return self.exif.get('ISOSpeedRatings')

    @cached_property
    def exif(self):
        key = 'photoexif{}'.format(self.pk)
        data = cache.get(key)
        if data is None:
            with Image.open(self.file) as image:
                exif = image._getexif()
            data = {}
            for key in exif:
                data[TAGS.get(key, key)] = exif[key]
            cache.set(key, data)
        return data

photos/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from rest_framework.reverse import reverse


class User(AbstractUser):
    domain = models.CharField(max_length=200, blank=True, db_index=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.is_staff = True
        super().save(*args, **kwargs)

    @property
    def last_photo(self):
        return self.photos.last()

    def get_absolute_url(self):
        if self.domain:
            return "http://{self.domain}".format(self=self)
        return reverse('user_home', args=[self.username])

photos/gallery/views.py
# -*- coding: utf-8 -*-
import logging

from django.core.urlresolvers import reverse
from django.http.response import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from photos.gallery.serializers import PhotoSerializer
from photos.users.models import User
from .models import Photo

logger = logging.getLogger(__name__)


class PhotoViewMixin(object):
    model = Photo

    def custom_domain(self):
        host = self.request.get_host()
        return host != 'photos.mocco.no' and host != '127.0.0.1:8000'

    def dispatch(self, *args, **kwargs):
        username = self.kwargs.get('username', None)

        if username and self.custom_domain():
            raise Http404()

        if username:
            user = User.objects.get(username=username)
            if user.domain:
                return redirect("http://{domain}{path}".format(
                    domain=user.domain,
                    path=self.request.get_full_path().replace(r'^/u/{0}'.format(username), '')
                ))

        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs.get('username', None)

        if self.custom_domain():
            context['photographer'] = User.objects.get(domain=self.request.get_host())
            context['archive_url'] = reverse('gallery:archive')
        elif username:
            context['photographer'] = User.objects.get(username=username)
            context['archive_url'] = reverse('user_archive', args=[username])
        return context

    def get_queryset(self):
        queryset = self.model.objects.all()
        username = self.kwargs.get('username', None)

        if self.custom_domain():
            queryset = queryset.filter(user__domain=self.request.get_host())
        elif username is not None:
            queryset = queryset.filter(user__username=username)

        return queryset


class PhotoDetailView(PhotoViewMixin, DetailView):
    def get_object(self, queryset=None, **kwargs):
        queryset = queryset or self.get_queryset()
        slug = self.kwargs.get(self.slug_url_kwarg, None)

        if slug is None:
            return queryset.last()
        return get_object_or_404(queryset, slug=slug)


class ArchiveView(PhotoViewMixin, ListView):
    pass


class ArchiveApiView(PhotoViewMixin, ListView):
    def get(self, request, *args, **kwargs):
        return JsonResponse(PhotoSerializer(self.get_queryset(), many=True).data, safe=False)

photos/views.py
from django.shortcuts import render

from photos.gallery.views import PhotoDetailView

from .users.models import User


def index(request):
    if request.get_host() == 'photos.mocco.no' or request.get_host() == '127.0.0.1:8000':
        return render(request, 'index.html', {
            'users': User.objects.filter(is_active=True)
        })
    return PhotoDetailView.as_view()(request)

photos/gallery/templates/gallery/photo_detail.html
{% extends 'base.html' %}

{% block extra_meta %}
  <meta name="twitter:card" content="photo" />
  <meta name="twitter:site" content="@moccoas" />
  <meta name="twitter:title" content="{{ object.title }}" />
  <meta name="twitter:image" content="http://{{ request.get_host }}{{ object.medium_thumbnail.url }}" />
  <meta name="twitter:url" content="{{ object.get_absolute_url }}" />
{% endblock %}

{% block content %}
  {% if archive_url %}
    <div class="nav">
        <a href="{{ archive_url }}">Archive</a>
    </div>
  {% endif %}

  <div class="image" style="background-image: url({{ object.large_thumbnail.url }})"></div>
  <div class="meta">
    <div class="info">
      <h1>{{ object.title }}</h1>
      {{ object.camera }} - {{ object.focal_length }}mm {{ object.exposure_time }}s
      f/{{ object.aperture }}
    </div>
  </div>
{% endblock %}

{% block js %}
  <script>
    setTimeout(function () {
      var el = document.querySelector('.meta');
      el.classList.add('hidden');
    }, 1000);
  </script>
{% endblock %}

photos/gallery/templates/gallery/photo_list.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center">Photos by {{ photographer.get_full_name }}</h1>
  <ul class="archive">
    {% for photo in object_list %}
      <li>
        <a href="{% url 'gallery:photo_detail' photo.slug %}" style="background-image: url({{ photo.archive_thumbnail.url }});">
          <span class="title">&nbsp;&nbsp;{{ photo.title }}</span>
        </a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

photos/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>Photos</title>
  <link href="http://fonts.googleapis.com/css?family=Raleway:600,400,100" rel="stylesheet"/>
  <link href="{% static 'main.css' %}" rel="stylesheet" />
  {% block css %}{% endblock %}

  {% block extra_meta %}{% endblock %}
</head>
<body>
  <div class="wrapper {% if object %}photo-details{% endif %}">
    {% block content %}{% endblock %}
  </div>
{% block js %}{% endblock %}
</body>
</html>

photos/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center">Photographers</h1>
  <ul class="archive">
    {% for user in users %}
      <li>
        <a href="{{ user.get_absolute_url }}" style="background-image: url({{ user.last_photo.archive_thumbnail.url }});">
          <span class="title">&nbsp;&nbsp;{{ user.get_full_name }}</span>
        </a>
      </li>
    {% endfor %}
  </ul>
  
  <div class="index-actions">
    <a href="/login/twitter">Login with Twitter</a>
  </div>
{% endblock %}